command:
  - bash
  - -lc
  - |
    set -euo pipefail

    # Install including devDependencies so "react-router build" is available
    export NPM_CONFIG_PRODUCTION=false
    npm ci

    # Build the app (VITE_* gets baked in here)
    npm run build

    # Start server on the Databricks-assigned port
    export HOST="0.0.0.0"
    export PORT="${DATABRICKS_APP_PORT}"
    export NODE_ENV="production"

    # Use npm to resolve the local binary instead of `npx`
    npm start
env:
  - name: VITE_API_ROOT_API_URL
    value: https://team-3si-dashboard-api.vercel.app/api/v1
  # Quiet the tsconfck noise caused by scanning external tsconfigs
  - name: TSCONFCK_IGNORE_CONFIG_ERRORS
    value: "true"



